/* mconsts.h: mathematical constants */

/**
 * \file include/shg/mconsts.h
 *  Mathematical constants.
 * \date Created on 17 July 2014.
 */

#ifndef SHG_MCONSTS_H
#define SHG_MCONSTS_H

namespace SHG {

/**
 * Mathematical constants.
 */
namespace Constants {

/**
 * \defgroup mathematical_constants Mathematical constants
 *
 * Some mathematical constants. Some of the approximations were
 * generated by the following program:
 *
 * \verbinclude gmconsts.cc
 *
 * \{
 */

/**
 * Returns the constant \f$\pi = 3.14\ldots\f$. The approximation is
 * taken from \cite knuth-2002a, p. 647.
 */
template<class T> inline T pi() {
     return static_cast<T>(3.1415926535897932384626433832795028841972L);
}

/**
 * Returns the constant \f$e = 2.718\ldots\f$. The approximation is
 * taken from \cite knuth-2002a, p. 647.
 */
template<class T> inline T e() {
     return static_cast<T>(2.7182818284590452353602874713526624977572L);
}

/**
 * Returns the constant \f$\gamma = 0.577\ldots\f$. The approximation
 * is taken from \cite knuth-2002a, p. 647.
 */
template<class T> inline T gamma() {
     return static_cast<T>(0.5772156649015328606065120900824024310422L);
}

/**
 * Returns the constant \f$1 / \pi\f$. The approximation is taken from
 * \cite knuth-2002a, p. 647.
 */
template<class T> inline T ipi() {
     return static_cast<T>(0.3183098861837906715377675267450287240689L);
}

/**
 * Returns the constant \f$1 / \sqrt{2\pi}\f$.
 */
template<class T> inline T isqrt2pi() {
     return static_cast<T>(0.3989422804014326779399460599343818684759L);
}

/**
 * Returns the constant \f$\sqrt{2\pi}\f$.
 */
template<class T> inline T sqrt2pi() {
     return static_cast<T>(2.5066282746310005024157652848110452530070L);
}

/**
 * Returns the constant \f$1 / \ln 2\f$. See \cite knuth-2002a, p.
 * 647.
 */
template<class T> inline T iln2() {
     return static_cast<T>(1.4426950408889634073599246810018921374266L);
}

/**
 * Returns the constant \f$\sqrt{2}\f$.
 */
template<class T> inline T sqrt2() {
     return static_cast<T>(1.4142135623730950488016887242096980785697L);
}

/**
 * Returns the constant \f$1 / \sqrt{2}\f$.
 */
template<class T> inline T isqrt2() {
     return static_cast<T>(0.7071067811865475244008443621048490392848L);
}

/**
 * Returns the constant \f$\pi^2 / 8\f$.
 */
template<class T> inline T sqrpi8() {
     return static_cast<T>(1.2337005501361698273543113749845188919142L);
}

/** \} */       // end of group mathematical_constants

}       // namespace Constants

}       // namespace SHG

#endif
